### ISSUE TITLE
Commit edd99f33fe06cfdf3cf1d74e28f921366f59a56b broke Max31855 and maybe other sensors

### ISSUE THREAD

**Issue by sendel** [Smoothieware/Smoothieware#1501]
It read temperature by Idle, but it not good state for read, and temperature can not change long time. And it add on_idle to Max31855.cpp/.h but other sensors havent it function.

**Comment by wolfmanjm** [comment]
on_idle() is the only place SPI can be read, it runs about every 100ms so is perfectly adequate for temperature readings.
I suggest that your problem is that you either do not have a functioning SPI or are using the wrong SPI port.
I do not think it has anything to do with updates happening in on_idle().

**Comment by arthurwolf** [comment]
Can you describe more precisely what you mean by "havent it function"? What exactly are you seeing that is an issue?

**Comment by sendel** [comment]
> Can you describe more precisely what you mean by "havent it function"? What exactly are you seeing that is an issue?

Not shure, but on_idle function Im found only for Max31855, and not know what will be when idle process call sensor.on_idle for other sensor, Thermistor for example. And other "problem" Max31855 havent function/params that have other sensors, void get_raw(); and float min_temp, max_temp;

**Comment by arthurwolf** [comment]
What do you mean you're not sure? If something is not working correctly, you should be able to tell us what is not working. Are you sure anything is in fact not working ??
