### ISSUE TITLE
G92 latency for closed loop offset/correction on the fly

### ISSUE THREAD

**Issue by Juanduino** [Smoothieware/Smoothieware#1524]
Dear all

Im doing a CNC build and in that process, im researching how a simple low cost closed loop “sub_driver” could be implemented. 

Have been going back and forth with the UGS crew about doing a virtual machine closed loop implementation as a UGS plugin, but there are several drawbacks. 

https://github.com/winder/Universal-G-Code-Sender/discussions/1967

Arguments against doing it would be:

Mainly Latency. 

Those hybrid-stepper add on things are very cheap. 

How would you implement a dedicated encoder/decoder sub_driver using the Arduino encoder lib by Paul@Teensy or the hardware QDEC on STM MCUs (which can possibly work w. Several encoders). 

One argument for streaming the sensed (physical) positions into UGS is the human/machine interface/learning/awareness part of it. I see some potential for comparing the physical position w. Gcode path in order to correct any offset by eg. G92 offset. That would involve some latency, but may still safe a print or CNC job from going bad, since it will correct lost steps before they possibly accumulate and the user would become aware of it.

Another option, I guess, would be to hook up the encoder “sub driver” to smoothie?

How fast does smoothieware implement G92 ? Can it be optimized?

Edit: Here is a real world use_case scenario. Have you ever experienced your 3D print warping and the nozzle thereby hitting some obstacle not meant to be there. This can lead to a very creative waste of filament. If the above closed loop where monitoring the printer progress, constantly comparing the actual nozzle position with the Gcode path, the print would be paused as soon as the physical nozzle location would deviate more then a pre-set margin. It could also be stringing, leading to blobs, which can push the head off course. Not the ideal situation, but sometimes it happens.

**Comment by harlock999** [comment]
Hi,
I have made an outside closed loop with Smoothieware, a bit like you described. In my case I have an analog signal that is scaled to the position of the head vs my workpiece. Basically I had an external PLC that scaled the analog signal and based on amount of position error, triggers a step up or a step down to Smoothie. I tinkered with baby-step but that didn't work for me, now I've seen in some forums there is maybe a bug with it. I ended up modifying the firmware and making my own bypass Z-correction similar to baby step, but without any compensation for position. It works well but Smoothie looses track of where the head is, so you may want to do Z-homing before each job. In some way I feel fine with Smoothie not recording about the position change as any Z movement from the G-code will perform as expected. The biggest drawback is because I'm using an external PLC, the external PLC doesn't quite know when the job is done, so quite a bit of logic and testing is needed to cover *most* of the cases.

I don't have issues with latency or job defects but then it may be specific to my setup.

**Comment by Juanduino** [comment]
Nicely done!

So the analog value is part of the smoothieware planner or where exactly does it add or subtract the steps? Can it correct already planed moves by a step or two? 

Homing before a job is definitely advisable.

Another way would be to introduce a new Gcode command to offset already planned moves or moves being executed.

**Comment by harlock999** [comment]
Smoothie is unaware of the analog value. Math and logic are done externally with the PLC, you can probably use an arduino derivative to do the same task. Depending on your implementation it can be very complex. In my case it corrects by a certain amount of steps every 10ms or so. Note that I barely use the Z movements so this is why my approach works.

If you plan to work in the Smoothie firmware code, be careful not to mess too much with the planner code. This is somewhat key to maintain a smooth toolpath.

**Comment by Juanduino** [comment]
Ok, it’s just for Z axis. Still it’s nice.

I was thinking to have the combined position for X, Y (Y1&2) and Z being streamed into UGS, from a single MCU via USB packets holding the entire coordinate. The UGS plug-in should maybe just hold the Gcode path which it streams to smoothieware and discard what has already been passed (compared) that should make the program less memory heavy. 

hmm, delta machines would require some clever math in the plug-in or on the MCU.

**Comment by wolfmanjm** [comment]
As mentioned this needs to be done by an external processor and cannot be done within smoothie.

G92 is queued along with all other GCodes so cannot be made to work immediately.
