### ISSUE TITLE
wrong config option in example config

### ISSUE THREAD

**Issue by Bouni** [Smoothieware/Smoothieware#655]
Hi,

there is an error in the [config example](https://github.com/Smoothieware/Smoothieware/blob/edge/ConfigSamples/Smoothieboard/config#L198).

The example says `switch.spindle.enable` but the [code expects](https://github.com/Smoothieware/Smoothieware/blob/edge/src/modules/tools/spindle/Spindle.cpp#L27) `spindle_enable`.

Should i submit a pull request for this minor change?

**Comment by arthurwolf** [comment]
It's not an error.
Using a switch module, or using the spindle module, are two different ways
of controlling a spindle, both valid.

But it looks like the spindle module doesn't have an example in the config
files, so that should probably be fixed.

On Mon, Apr 13, 2015 at 3:03 PM, bouni <notifications@github.com> wrote:

> Hi,
>
> there is an error in the config example
> <https://github.com/Smoothieware/Smoothieware/blob/edge/ConfigSamples/Smoothieboard/config#L198>
> .
>
> The example says switch.spindle.enable but the code expects
> <https://github.com/Smoothieware/Smoothieware/blob/edge/src/modules/tools/spindle/Spindle.cpp#L27>
> spindle_enable.
>
> Should i submit a pull request for this minor change?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/issues/655>.
>



-- 
Courage et bonne humeur.

**Comment by Bouni** [comment]
Ah, ok, then i got that wrong. But it would make sense to provide a mill/router config example anyway!
